//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leibit.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Leibit.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;leibit&gt;
        ///  &lt;area id=&quot;myTestArea&quot; name=&quot;Testland&quot;&gt;
        ///    &lt;estw id=&quot;TTST&quot; name=&quot;Testdorf&quot; dataFile=&quot;leibit_TEST.dat&quot;&gt;
        ///      &lt;station name=&quot;Linksdorf&quot; short=&quot;TLDF&quot; refNr=&quot;30&quot;&gt;
        ///        &lt;track isPlatform=&quot;false&quot; calculateDelay=&quot;false&quot;&gt;
        ///          &lt;block name=&quot;30BN&quot; direction=&quot;right&quot; /&gt;
        ///          &lt;block name=&quot;31B4711&quot; direction=&quot;right&quot; /&gt;
        ///        &lt;/track&gt;
        ///      &lt;/station&gt;
        ///      
        ///      &lt;station name=&quot;Probe&quot; short=&quot;TPRB&quot; refNr=&quot;31&quot; scheduleFile=&quot;g31_____.abf&quot; localOrd [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LeibitData {
            get {
                return ResourceManager.GetString("LeibitData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestData\ESTWRoots\Rechtsheim.
        /// </summary>
        public static string path_TREH {
            get {
                return ResourceManager.GetString("path_TREH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestData\ESTWRoots\Testdorf.
        /// </summary>
        public static string path_TTST {
            get {
                return ResourceManager.GetString("path_TTST", resourceCulture);
            }
        }
    }
}
